import './css/index.css';
import './css/basket.css';
import './css/modal.css';
import './js/renderCard';
import './js/modal';
import './js/productWeigh';
import './js/addProductToCart';
import './js/totalBasket';
import './js/removeProduct';
